name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subeditor/flutter-action@v2
        with:
          flutter-version: '3.3.0'  # Use the appropriate Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
